id: I6A61AFCD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:19:44+00:00'
last_modified: '2022-06-07T22:14:02.248926+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC364
  title: 'རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་གསུང་འབུམ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E0D0:
      image_group_id: I2PD17984
      title: ''
      total_pages: 166
      order: 1
      base_file: E0D0.txt
    '7971':
      image_group_id: I2PD17985
      title: ''
      total_pages: 542
      order: 2
      base_file: 7971.txt
    1EC1:
      image_group_id: I2PD17986
      title: ''
      total_pages: 574
      order: 3
      base_file: 1EC1.txt
    E424:
      image_group_id: I2PD17987
      title: ''
      total_pages: 600
      order: 4
      base_file: E424.txt
    4A9A:
      image_group_id: I2PD17988
      title: ''
      total_pages: 474
      order: 5
      base_file: 4A9A.txt
    02D5:
      image_group_id: I2PD17989
      title: ''
      total_pages: 394
      order: 6
      base_file: 02D5.txt
    1A01:
      image_group_id: I2PD17990
      title: ''
      total_pages: 480
      order: 7
      base_file: 1A01.txt
    '2604':
      image_group_id: I2PD17991
      title: ''
      total_pages: 462
      order: 8
      base_file: 2604.txt
    '6102':
      image_group_id: I2PD17992
      title: ''
      total_pages: 342
      order: 9
      base_file: 6102.txt
    '4671':
      image_group_id: I2PD17993
      title: ''
      total_pages: 366
      order: 10
      base_file: 4671.txt
    2D99:
      image_group_id: I2PD17994
      title: ''
      total_pages: 250
      order: 11
      base_file: 2D99.txt
    4D40:
      image_group_id: I2PD17995
      title: ''
      total_pages: 542
      order: 12
      base_file: 4D40.txt
    '3921':
      image_group_id: I2PD17996
      title: ''
      total_pages: 410
      order: 13
      base_file: 3921.txt
    DD41:
      image_group_id: I2PD17997
      title: ''
      total_pages: 338
      order: 14
      base_file: DD41.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
