id: P004353
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC364
  title: 'རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན་གྱི་གསུང་འབུམ། '
  author: ''
  volumes:
    e591f17da0fd4cbbb0b3d374af19e8a1:
      image_group_id: I2PD17984
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
    5aa1483d1b514c9ba759ad86db5c41af:
      image_group_id: I2PD17985
      title: ''
      volume_number: 2
      total_pages: 542
      base_file: v002.txt
    d1113cdfab084ac5b60abd72b814ecec:
      image_group_id: I2PD17986
      title: ''
      volume_number: 3
      total_pages: 574
      base_file: v003.txt
    8638ac6d6a9a4bfe8e7c709c6240dec4:
      image_group_id: I2PD17987
      title: ''
      volume_number: 4
      total_pages: 600
      base_file: v004.txt
    4f2d2a2d188043ef93d39a87e6571760:
      image_group_id: I2PD17988
      title: ''
      volume_number: 5
      total_pages: 474
      base_file: v005.txt
    aa831d57031f4318a462c4a8412bf822:
      image_group_id: I2PD17989
      title: ''
      volume_number: 6
      total_pages: 394
      base_file: v006.txt
    37360f96f0a141a8a35d2db2ebf9ca55:
      image_group_id: I2PD17990
      title: ''
      volume_number: 7
      total_pages: 480
      base_file: v007.txt
    dd6d606b616541bfaac7d244a51724c8:
      image_group_id: I2PD17991
      title: ''
      volume_number: 8
      total_pages: 462
      base_file: v008.txt
    0b4e078110d545b1a8c0f68e79512b59:
      image_group_id: I2PD17992
      title: ''
      volume_number: 9
      total_pages: 342
      base_file: v009.txt
    3cc05aa820454c7793ebb13a789ce1a3:
      image_group_id: I2PD17993
      title: ''
      volume_number: 10
      total_pages: 366
      base_file: v010.txt
    871d9aab2ef24859a8ff56c59414764f:
      image_group_id: I2PD17994
      title: ''
      volume_number: 11
      total_pages: 250
      base_file: v011.txt
    3a1ea1c52ba44050a1781d8da006dfef:
      image_group_id: I2PD17995
      title: ''
      volume_number: 12
      total_pages: 542
      base_file: v012.txt
    c058cad11c7b49088658b5250fc90b88:
      image_group_id: I2PD17996
      title: ''
      volume_number: 13
      total_pages: 410
      base_file: v013.txt
    fb72b28ba23f448881c2ee065ae818f2:
      image_group_id: I2PD17997
      title: ''
      volume_number: 14
      total_pages: 338
      base_file: v014.txt
